CREATE TABLE CLIENTE (
CLIENTE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CLIENTE_NOME VARCHAR(255), 
CLIENTE_SOBRENOME VARCHAR(255),
CLIENTE_CPF VARCHAR(100), 
CLIENTE_RG VARCHAR(255), 
CLIENTE_RUA VARCHAR(255), 
CLIENTE_NUMERO VARCHAR(255),
CLIENTE_COMPLEMENTO  VARCHAR(100),
CLIENTE_BAIRRO  VARCHAR(100),
CLIENTE_CIDADE VARCHAR(255), 
CLIENTE_CEP  VARCHAR(100),
CLIENTE_NASCIMENTO VARCHAR(255), 
CLIENTE_EMAIL  VARCHAR(100),
CLIENTE_SEXO VARCHAR(255),
CLIENTE_CELULAR VARCHAR(255),
CLIENTE_TELEFONE VARCHAR(255));


/*
INSERT INTO CLIENTE (NOME_CLIENTE,
CPF_CLIENTE,
RG_CLIENTE, 
SEXO_CLIENTE,
EMAIL_CLIENTE,
NASCIMENTO_CLIENTE,
TEL_FIXO_CLIENTE,
TEL_CEL_CLIENTE,
END_RUA_CLIENTE,
END_NUM_CLIENTE,
END_BAIRRO_CLIENTE,
END_CEP_CLIENTE, 
END_EST_CLIENTE,
END_CID_CLIENTE,
END_COMP_CLIENTE,
EST_CIVIL_CLIENTE) VALUES ('Paula Silva','330550660','382638147','Feminino','paula@paula.com.br','14/08/1968','58135412','930254178','Rua Tião','1000',
'Parque São Judas','05762221','RJ','Região dos lagos','Bloco A ALA C','Solteira');*/

