CREATE TABLE FILIAL (ID_FILIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    END_RUA_FILIAL VARCHAR(255),
                    END_NUM_FILIAL VARCHAR(255),
                    END_CEP_FILIAL VARCHAR(255),
                    END_EST_FILIAL VARCHAR(255),
                    END_CID_FILIAL VARCHAR(255),
                    END_BAIRRO_FILIAL VARCHAR(255),
                    END_COMP_FILIAL VARCHAR(255),
                    CNPJ_FILIAL VARCHAR(255),
                   NOME_FANTASIA_FILIAL VARCHAR(255))

INSERT INTO `filial`(`END_RUA_FILIAL`, `END_NUM_FILIAL`, `END_CEP_FILIAL`, `END_EST_FILIAL`, `END_CID_FILIAL`, `END_BAIRRO_FILIAL`, `END_COMP_FILIAL`, `CNPJ_FILIAL`, `NOME_FANTASIA_FILIAL`) VALUES ('Rua Vergo Filho','200','05762-220','São Paulo','São Paulo','Centro','Predio A2','34.534.531/2312-31','Black')

