CREATE TABLE CONTRATO (
ID_CONTRATO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_COMPRADOR INT,
ID_IMOVEL INT,
ID_PROPRIETARIO INT,
ID_FILIAL INT,
ID_CORRETOR INT,
DATA_CONTRATO VARCHAR(255)));

INSERT INTO `contrato`( `ID_COMPRADOR`, `ID_IMOVEL`, `ID_PROPRIETARIO`, `DATA_CONTRATO`) VALUES (1,1,1,1,1,'10/06/2017');